# Generated by Django 3.0.4 on 2020-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_ip',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
