# Generated by Django 3.0.4 on 2020-03-24 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('remote_addr', models.CharField(blank=True, max_length=512)),
                ('remote_addr_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_ip', models.CharField(blank=True, max_length=16)),
                ('remote_addr', models.CharField(blank=True, max_length=16, null=True)),
                ('request_time', models.CharField(blank=True, max_length=32, null=True)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('protocol', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('exist', models.BooleanField(blank=True, default=True)),
                ('time_iso8601', models.CharField(blank=True, max_length=512, null=True)),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
            ],
            options={
                'db_table': 'request_data',
                'managed': True,
            },
        ),
    ]
