# Generated by Django 3.0.4 on 2020-03-23 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('remote_addr', models.CharField(blank=True, max_length=512)),
                ('remote_addr_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_ip', models.CharField(blank=True, max_length=16)),
                ('remote_addr', models.CharField(blank=True, max_length=512, null=True)),
                ('http_x_forwarded_for', models.CharField(blank=True, max_length=512, null=True)),
                ('remote_user', models.CharField(blank=True, max_length=512, null=True)),
                ('request', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=512, null=True)),
                ('body_bytes_sent', models.CharField(blank=True, max_length=512, null=True)),
                ('bytes_sent', models.CharField(blank=True, max_length=512, null=True)),
                ('connection', models.CharField(blank=True, max_length=512, null=True)),
                ('connection_requests', models.CharField(blank=True, max_length=512, null=True)),
                ('msec', models.CharField(blank=True, max_length=512, null=True)),
                ('pipe', models.CharField(blank=True, max_length=512, null=True)),
                ('http_referer', models.CharField(blank=True, max_length=512, null=True)),
                ('request_length', models.CharField(blank=True, max_length=512, null=True)),
                ('request_time', models.CharField(blank=True, max_length=512, null=True)),
                ('exist', models.BooleanField(default=True)),
                ('time_iso8601', models.CharField(blank=True, max_length=512, null=True)),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
            ],
            options={
                'db_table': 'request_data',
                'managed': True,
            },
        ),
    ]
