# Generated by Django 3.0.4 on 2020-03-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('remote_addr', models.CharField(blank=True, max_length=512, null=True)),
                ('http_x_forwarded_for', models.CharField(blank=True, max_length=512, null=True)),
                ('remote_user', models.CharField(blank=True, max_length=512, null=True)),
                ('request', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=512, null=True)),
                ('body_bytes_sent', models.CharField(blank=True, max_length=512, null=True)),
                ('bytes_sent', models.CharField(blank=True, max_length=512, null=True)),
                ('connection', models.CharField(blank=True, max_length=512, null=True)),
                ('connection_requests', models.CharField(blank=True, max_length=512, null=True)),
                ('msec', models.CharField(blank=True, max_length=512, null=True)),
                ('pipe', models.CharField(blank=True, max_length=512, null=True)),
                ('http_referer', models.CharField(blank=True, max_length=512, null=True)),
                ('request_length', models.CharField(blank=True, max_length=512, null=True)),
                ('request_time', models.CharField(blank=True, max_length=512, null=True)),
                ('time_iso8601', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
