# Generated by Django 3.0.4 on 2020-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
