# Generated by Django 3.0.4 on 2020-03-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdata',
            name='time_iso8601',
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='agent_ip',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
