# Generated by Django 3.0.4 on 2020-03-21 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0002_auto_20200321_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
    ]
