# Generated by Django 3.0.4 on 2020-03-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0002_auto_20200324_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='protocol',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
