# Generated by Django 3.0.4 on 2020-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0003_auto_20200324_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
