# Generated by Django 3.0.4 on 2020-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsserver', '0005_requestdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdata',
            name='country',
        ),
        migrations.AddField(
            model_name='requestdata',
            name='city_name',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='city_name_cn',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='continent',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='continent_cn',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='country_name',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='country_name_cn',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='country_specific_name',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='country_specific_name_cn',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
    ]
